# Generated by Django 3.0.8 on 2020-08-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eno',
            new_name='enom',
        ),
    ]
